function p = vaeDefaultParams()
% vaeDefaultParams Default training parameters for trainGenerativeModel
%   reconLossType 'auto' resolves to BCE for grayscale and MSE for colour data.
%   maxImages 0 means "use every training image".

    p = struct( ...
        'latentDim', 16, ...
        'epochs', 20, ...
        'batchSize', 128, ...
        'learnRate', 1e-3, ...
        'seed', 1, ...
        'maxImages', 10000, ...
        'beta', 1, ...
        'reconLossType', 'auto', ...
        'numSamples', 16);
end
