function p = defaultTrainingParams()
% defaultTrainingParams The parameter struct TrainingCNN.collectParams builds, with the
%   defaults of the window's controls. Scripts start from this and override fields.
%
%   validationFrequency 0 means "once per epoch" (see trainCNNModel); the window's
%   spinner cannot produce it. validationPatience / gradientThreshold use Inf for "off",
%   as collectParams does. Optional fields: verbose (false), subsetFraction (1).

    p = struct( ...
        'lr', 1e-3, ...
        'batchSize', 64, ...
        'epochs', 5, ...
        'weightDecay', 5e-4, ...
        'optimizer', 'sgdm', ...
        'momentum', 0.9, ...
        'beta1', 0.9, ...
        'beta2', 0.999, ...
        'rmsDecay', 0.9, ...
        'epsilon', 1e-8, ...
        'validationFraction', 0.10, ...
        'validationFrequency', 50, ...
        'validationPatience', 5, ...
        'gradientThreshold', Inf, ...
        'shuffle', 'every-epoch', ...
        'plots', 'training-progress', ...
        'augment', false, ...
        'executionEnvironment', 'cpu', ...
        'verbose', false, ...
        'subsetFraction', 1);
end
