function options = getTrainingOptions(p, validationData)
% getTrainingOptions trainingOptions from the parameter struct of TrainingCNN
%   p.verbose (optional, default false) turns on MATLAB's console training log.
%   Supports sgdm, adam and rmsprop; anything else errors.

    verbose = isfield(p, 'verbose') && p.verbose;
    common = {
        'InitialLearnRate', p.lr, ...
        'MaxEpochs', p.epochs, ...
        'MiniBatchSize', p.batchSize, ...
        'L2Regularization', p.weightDecay, ...
        'GradientThreshold', p.gradientThreshold, ...
        'Shuffle', p.shuffle, ...
        'Verbose', verbose, ...
        'Plots', p.plots, ...
        'ExecutionEnvironment', p.executionEnvironment};
    if ~isempty(validationData)
        common = [common, {
            'ValidationData', validationData, ...
            'ValidationFrequency', p.validationFrequency, ...
            'ValidationPatience', p.validationPatience}];
    end

    switch p.optimizer
        case 'sgdm'
            options = trainingOptions('sgdm', common{:}, ...
                'Momentum', p.momentum);
        case 'adam'
            options = trainingOptions('adam', common{:}, ...
                'GradientDecayFactor', p.beta1, ...
                'SquaredGradientDecayFactor', p.beta2, ...
                'Epsilon', p.epsilon);
        case 'rmsprop'
            options = trainingOptions('rmsprop', common{:}, ...
                'SquaredGradientDecayFactor', p.rmsDecay, ...
                'Epsilon', p.epsilon);
        otherwise
            error('Unsupported optimizer: %s', p.optimizer);
    end
end
